print()
print("           Tugas Kedua")
print("=="*20)
panjang=int(input("Masukkan Panjang     = "))
lebar=int(input("Masukkan Lebar       = "))
tinggi=int(input("Masukkan Tinggi      = "))
print("    Panjang          =",panjang,"cm")
print("    Lebar            =",lebar,"cm")
print("    tinggi           =",tinggi,"cm")
luas=2*(panjang*lebar+panjang*tinggi+lebar*tinggi)
volume=panjang*lebar*tinggi
print("Luas Permukaan Balok =",luas,"cm2")
print("Volume balok         =",volume,"cm3")
print("=="*20)